name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Build
      run: make linux
    - name: Upload
      uses: actions/upload-artifact@v3.1.0
      with:
        name: csgo_linux64
        path: ./csgo_linux64
        
